services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ../.pg_data:/var/lib/postgresql/data
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../apps/api/.env.docker
    depends_on:
      - postgres
  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../apps/web/.env.docker
    depends_on:
      - postgres
      - api
